import React, { useState } from 'react';
import { 
  FileText, 
  MessageSquare, 
  Instagram, 
  CheckCircle2, 
  Copy, 
  ShieldCheck, 
  Sparkles,
  Globe,
  Share2
} from 'lucide-react';
import { INDIAN_LANGUAGES } from '@ai-marketing/shared';

interface ContentStudioProps {
  contentAssets: any[];
}

export const ContentStudio: React.FC<ContentStudioProps> = ({ contentAssets }) => {
  const [selectedLanguage, setSelectedLanguage] = useState<string>('ALL');
  const [selectedChannel, setSelectedChannel] = useState<string>('ALL');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const channels = ['ALL', 'WHATSAPP', 'INSTAGRAM', 'GOOGLE_BUSINESS_PROFILE', 'META_ADS', 'EMAIL'];

  const filteredAssets = contentAssets.filter(asset => {
    const matchesLang = selectedLanguage === 'ALL' || asset.language === selectedLanguage;
    const matchesChan = selectedChannel === 'ALL' || asset.channel === selectedChannel;
    return matchesLang && matchesChan;
  });

  const handleCopy = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-extrabold text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            Multi-Lingual Content Studio
          </h2>
          <p className="text-slate-400 text-xs mt-1">
            Generated by 20 Content Agents, QA verified for Medical & Advertising compliance, and scored for Brand Voice fidelity.
          </p>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 rounded-xl bg-slate-900 border border-slate-800">
        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-400 font-semibold">Channel:</span>
          <div className="flex flex-wrap gap-1">
            {channels.map(ch => (
              <button
                key={ch}
                onClick={() => setSelectedChannel(ch)}
                className={`px-2.5 py-1 rounded text-xs font-semibold transition-all ${
                  selectedChannel === ch 
                    ? 'bg-cyan-500 text-slate-950 font-bold' 
                    : 'bg-slate-800 text-slate-400 hover:text-slate-200'
                }`}
              >
                {ch}
              </button>
            ))}
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Globe className="w-4 h-4 text-slate-400" />
          <select
            value={selectedLanguage}
            onChange={(e) => setSelectedLanguage(e.target.value)}
            className="px-3 py-1 bg-slate-800 border border-slate-700 rounded text-xs text-slate-200 focus:outline-none focus:border-cyan-500"
          >
            <option value="ALL">All Languages</option>
            {INDIAN_LANGUAGES.map(lang => (
              <option key={lang.code} value={lang.name}>
                {lang.name} ({lang.nativeName})
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Assets Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {(filteredAssets.length > 0 ? filteredAssets : [
          {
            id: 'cnt_wa_demo',
            title: 'Clear Aligners Consultation Offer',
            channel: 'WHATSAPP',
            language: 'English',
            content: 'Hi! Looking for pain-free smile alignment in Banjara Hills? SmileKraft Dental brings you US-FDA approved invisible aligners with 3D smile preview.\n\n✨ 100% Invisible & Removable\n✨ Easy EMI starting at ₹2,999/month\n✨ 0% interest with Bajaj Finserv\n\nBook your 3D Smile Scan this week and receive ₹5,000 treatment credit!',
            call_to_action: 'Reply "SMILE" to book your 3D Scan',
            brand_voice_score: 0.95,
            factual_confidence: 0.98,
            status: 'APPROVED',
            target_funnel_stage: 'CONSIDERATION'
          },
          {
            id: 'cnt_gmb_demo',
            title: 'Painless Laser Teeth Whitening',
            channel: 'GOOGLE_BUSINESS_PROFILE',
            language: 'English',
            content: 'Getting ready for the wedding season in Hyderabad? Get up to 8 shades brighter in just 1 hour with our painless laser teeth whitening at SmileKraft Banjara Hills. Safe on enamel, long-lasting results.',
            call_to_action: 'Book appointment via Google Business Profile',
            brand_voice_score: 0.92,
            factual_confidence: 0.97,
            status: 'APPROVED',
            target_funnel_stage: 'AWARENESS'
          }
        ]).map((asset: any) => (
          <div key={asset.id} className="p-5 rounded-xl bg-slate-900 border border-slate-800 flex flex-col justify-between space-y-4 shadow-sm">
            <div>
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <span className="px-2 py-0.5 rounded text-[11px] font-bold bg-slate-800 text-cyan-400 border border-slate-700">
                    {asset.channel}
                  </span>
                  <span className="px-2 py-0.5 rounded text-[11px] font-medium bg-slate-800 text-slate-300">
                    {asset.language}
                  </span>
                </div>
                <span className="flex items-center gap-1 text-xs text-emerald-400 font-semibold">
                  <ShieldCheck className="w-3.5 h-3.5" />
                  {asset.status}
                </span>
              </div>

              <h3 className="font-bold text-sm text-slate-100 mb-2">{asset.title}</h3>

              <div className="p-3.5 rounded-lg bg-slate-850 border border-slate-800 text-xs text-slate-300 whitespace-pre-line leading-relaxed font-sans">
                {asset.content}
              </div>

              <div className="mt-3 p-2.5 rounded bg-slate-800/40 border border-slate-800 text-xs flex items-center justify-between">
                <span className="text-slate-400">Call to Action:</span>
                <span className="font-bold text-cyan-400">{asset.call_to_action}</span>
              </div>
            </div>

            <div className="pt-3 border-t border-slate-800 flex items-center justify-between text-xs text-slate-400">
              <div className="flex items-center gap-3 text-[11px]">
                <span>Voice: <strong className="text-slate-200">{(asset.brand_voice_score * 100).toFixed(0)}%</strong></span>
                <span>Factual: <strong className="text-slate-200">{(asset.factual_confidence * 100).toFixed(0)}%</strong></span>
              </div>

              <button
                onClick={() => handleCopy(asset.id, asset.content)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition-all"
              >
                {copiedId === asset.id ? (
                  <>
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Copied</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Text</span>
                  </>
                )}
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};