import React, { useState } from 'react';
import { 
  FileText, 
  MessageSquare, 
  Instagram, 
  CheckCircle2, 
  Copy, 
  ShieldCheck, 
  Sparkles, 
  Globe, 
  Share2,
  AlertCircle,
  Clock
} from 'lucide-react';
import { INDIAN_LANGUAGES } from '@ai-marketing/shared';

interface ContentStudioProps {
  contentAssets: any[];
  business?: any;
}

export const ContentStudio: React.FC<ContentStudioProps> = ({ contentAssets, business: propBusiness }) => {
  const [selectedLanguage, setSelectedLanguage] = useState<string>('ALL');
  const [selectedChannel, setSelectedChannel] = useState<string>('ALL');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const channels = ['ALL', 'WHATSAPP', 'INSTAGRAM', 'GOOGLE_BUSINESS_PROFILE', 'META_ADS', 'EMAIL'];

  const activeBiz = propBusiness || (() => {
    if (typeof window !== 'undefined') {
      try {
        const stored = localStorage.getItem('ai_marketing_active_business');
        if (stored) return JSON.parse(stored);
      } catch {}
    }
    return null;
  })();

  const bizName = activeBiz?.name || 'Local Business';
  const bizVertical = activeBiz?.vertical_name || 'Commercial Services';
  const bizCity = activeBiz?.city || 'India';
  const isHealthcare = /dental|health|clinic|doctor|hospital|ortho/i.test(bizVertical + ' ' + (activeBiz?.vertical_id || ''));

  // If no generated content assets exist in the system yet, provide dynamic preview templates customized per active business
  const dynamicPreviewTemplates = [
    {
      id: 'tpl_wa_intro',
      isTemplate: true,
      title: `${bizVertical} Client Consultation Invitation`,
      channel: 'WHATSAPP',
      language: 'English',
      content: `Hi! Looking for premier ${bizVertical.toLowerCase()} in ${bizCity}? ${bizName} offers tailored solutions backed by verified expertise and transparent pricing.\n\n✨ Certified Quality & Punctual Scheduling\n✨ Transparent fee structure with easy digital payments\n✨ Dedicated support in ${bizCity}\n\nContact ${bizName} this week to schedule your personalized consultation!`,
      call_to_action: `Reply "CONNECT" to schedule with ${bizName}`,
      brand_voice_score: 0.95,
      factual_confidence: 0.98,
      status: 'PREVIEW_TEMPLATE',
      target_funnel_stage: 'CONSIDERATION'
    },
    {
      id: 'tpl_gmb_spotlight',
      isTemplate: true,
      title: `${bizCity} Local Search Spotlight`,
      channel: 'GOOGLE_BUSINESS_PROFILE',
      language: 'English',
      content: `Looking for trusted ${bizVertical.toLowerCase()} in ${bizCity}? ${bizName} is open and accepting appointments. Verified client reviews, professional staff, and transparent quotes. Visit us or call today!`,
      call_to_action: `Book consultation with ${bizName}`,
      brand_voice_score: 0.94,
      factual_confidence: 0.99,
      status: 'PREVIEW_TEMPLATE',
      target_funnel_stage: 'AWARENESS'
    },
    {
      id: 'tpl_ig_showcase',
      isTemplate: true,
      title: `${bizName} Feature & Service Excellence`,
      channel: 'INSTAGRAM',
      language: 'English',
      content: `Excellence in ${bizVertical.toLowerCase()} right here in ${bizCity}. At ${bizName}, we prioritize quality outcomes, client satisfaction, and absolute integrity.\n\n📍 Serving ${bizCity} and surrounding neighborhoods\n💬 DM us or visit our link in bio to book your session!`,
      call_to_action: `Tap link in bio to connect with ${bizName}`,
      brand_voice_score: 0.92,
      factual_confidence: 0.97,
      status: 'PREVIEW_TEMPLATE',
      target_funnel_stage: 'CONSIDERATION'
    }
  ];

  const hasRealAssets = contentAssets && contentAssets.length > 0;
  const baseAssets = hasRealAssets ? contentAssets : dynamicPreviewTemplates;

  const filteredAssets = baseAssets.filter(asset => {
    const matchesLang = selectedLanguage === 'ALL' || asset.language === selectedLanguage;
    const matchesChan = selectedChannel === 'ALL' || asset.channel === selectedChannel;
    return matchesLang && matchesChan;
  });

  const handleCopy = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-extrabold text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            Multi-Lingual Content Studio
          </h2>
          <p className="text-slate-400 text-xs mt-1">
            Generated by 20 Content Agents, QA verified for statutory advertising compliance, and tuned for <strong className="text-cyan-300">{bizName}</strong>.
          </p>
        </div>
      </div>

      {!hasRealAssets && (
        <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/30 flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
          <div className="text-xs text-amber-200 leading-relaxed">
            <span className="font-bold text-amber-300">Preview Templates Active:</span> Below are dynamically customized starter templates generated for <strong className="text-white">{bizName}</strong> ({bizCity}). Once you run the autonomous workflow cycle or content agent pipeline, live AI-generated posts will automatically replace these previews.
          </div>
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 rounded-xl bg-slate-900 border border-slate-800">
        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-400 font-semibold">Channel:</span>
          <div className="flex flex-wrap gap-1">
            {channels.map(ch => (
              <button
                key={ch}
                onClick={() => setSelectedChannel(ch)}
                className={`px-2.5 py-1 rounded text-xs font-semibold transition-all ${
                  selectedChannel === ch 
                    ? 'bg-cyan-500 text-slate-950 font-bold' 
                    : 'bg-slate-800 text-slate-400 hover:text-slate-200'
                }`}
              >
                {ch}
              </button>
            ))}
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Globe className="w-4 h-4 text-slate-400" />
          <select
            value={selectedLanguage}
            onChange={(e) => setSelectedLanguage(e.target.value)}
            className="px-3 py-1 bg-slate-800 border border-slate-700 rounded text-xs text-slate-200 focus:outline-none focus:border-cyan-500"
          >
            <option value="ALL">All Languages</option>
            {INDIAN_LANGUAGES.map(lang => (
              <option key={lang.code} value={lang.name}>
                {lang.name} ({lang.nativeName})
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Assets Grid */}
      {filteredAssets.length === 0 ? (
        <div className="p-12 text-center rounded-xl bg-slate-900 border border-slate-800 space-y-2">
          <p className="text-sm font-semibold text-slate-300">No content assets found matching filter</p>
          <p className="text-xs text-slate-500">
            Selected Channel: <span className="text-cyan-400">{selectedChannel}</span> • Language: <span className="text-cyan-400">{selectedLanguage}</span>
          </p>
          <button
            onClick={() => { setSelectedChannel('ALL'); setSelectedLanguage('ALL'); }}
            className="mt-3 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs text-cyan-400 transition"
          >
            Reset Filters
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredAssets.map((asset: any) => (
            <div key={asset.id} className="p-5 rounded-xl bg-slate-900 border border-slate-800 flex flex-col justify-between space-y-4 shadow-sm">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span className="px-2 py-0.5 rounded text-[11px] font-bold bg-slate-800 text-cyan-400 border border-slate-700">
                      {asset.channel}
                    </span>
                    <span className="px-2 py-0.5 rounded text-[11px] font-medium bg-slate-800 text-slate-300">
                      {asset.language}
                    </span>
                  </div>
                  {asset.isTemplate ? (
                    <span className="flex items-center gap-1 text-[11px] text-amber-400 font-semibold px-2 py-0.5 rounded bg-amber-500/10 border border-amber-500/30">
                      <Clock className="w-3 h-3" />
                      Preview Template
                    </span>
                  ) : (
                    <span className="flex items-center gap-1 text-xs text-emerald-400 font-semibold">
                      <ShieldCheck className="w-3.5 h-3.5" />
                      {asset.status || 'APPROVED'}
                    </span>
                  )}
                </div>

                <h3 className="font-bold text-sm text-slate-100 mb-2">{asset.title}</h3>

                <div className="p-3.5 rounded-lg bg-slate-850 border border-slate-800 text-xs text-slate-300 whitespace-pre-line leading-relaxed font-sans">
                  {asset.content}
                </div>

                <div className="mt-3 p-2.5 rounded bg-slate-800/40 border border-slate-800 text-xs flex items-center justify-between">
                  <span className="text-slate-400">Call to Action:</span>
                  <span className="font-bold text-cyan-400">{asset.call_to_action}</span>
                </div>
              </div>

              <div className="pt-3 border-t border-slate-800 flex items-center justify-between text-xs text-slate-400">
                <div className="flex items-center gap-3 text-[11px]">
                  <span>Voice: <strong className="text-slate-200">{(asset.brand_voice_score * 100).toFixed(0)}%</strong></span>
                  <span>Factual: <strong className="text-slate-200">{(asset.factual_confidence * 100).toFixed(0)}%</strong></span>
                </div>

                <button
                  onClick={() => handleCopy(asset.id, asset.content)}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition-all"
                >
                  {copiedId === asset.id ? (
                    <>
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                      <span>Copied</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy Text</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};