import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

function getSecret(file, key) {
  if (!fs.existsSync(file)) return null;
  const content = fs.readFileSync(file, 'utf8');
  const match = content.match(new RegExp(`^${key}=(.*)$`, 'm'));
  return match ? match[1].trim() : null;
}

const renderApiKey = getSecret('.env.admin_secret', 'RENDER_API_KEY');
const cfToken = getSecret('.env.deploy_secrets', 'CLOUDFLARE_API_TOKEN');
const accountId = '9b7511ff69e507dd3a00a7266fec11a3';
const dbId = '0563bb85-f6d2-483f-8b0f-0784e3d604c7';
const renderServiceId = 'srv-darecoc9v7es73ea8t2g';

async function queryD1(sql) {
  if (!cfToken) return null;
  try {
    const res = await fetch(`https://api.cloudflare.com/client/v4/accounts/${accountId}/d1/database/${dbId}/query`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${cfToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ sql })
    });
    const data = await res.json();
    return data.result?.[0]?.results || [];
  } catch (err) {
    console.error('D1 query failed:', err.message);
    return null;
  }
}

async function getRenderDeploy() {
  if (!renderApiKey) return null;
  try {
    const res = await fetch(`https://api.render.com/v1/services/${renderServiceId}/deploys?limit=1`, {
      headers: {
        'Authorization': `Bearer ${renderApiKey}`,
        'Accept': 'application/json'
      }
    });
    const data = await res.json();
    return data[0]?.deploy || null;
  } catch (err) {
    console.error('Render query failed:', err.message);
    return null;
  }
}

async function main() {
  console.log('Generating PROJECT_STATUS.md from measured facts...');

  // 1. Git HEAD
  const gitHead = execSync('git rev-parse HEAD', { encoding: 'utf8' }).trim();
  const gitBranch = execSync('git branch --show-current', { encoding: 'utf8' }).trim();

  // 2. Render Deploy
  const deploy = await getRenderDeploy();

  // 3. Cloudflare D1
  const migrations = await queryD1('SELECT migration_name FROM _d1_migrations ORDER BY id DESC LIMIT 1;');
  const lastMigration = migrations?.[0]?.migration_name || 'UNKNOWN';

  const quotaRows = await queryD1('SELECT id, provider, provider_limit, application_limit, credits_consumed_month, source, limit_source, is_locked FROM provider_quota_state;');
  const mistakesRows = await queryD1('SELECT status, count(*) as count FROM mistakes_board GROUP BY status;');
  const driftRows = await queryD1('SELECT count(*) as count FROM provider_drift_records;');

  const tavilyQuota = quotaRows?.find(r => r.provider === 'TAVILY') || {};
  const geminiQuota = quotaRows?.find(r => r.provider === 'GEMINI') || {};

  const openMistakesCount = mistakesRows?.find(r => r.status === 'OPEN')?.count || 0;
  const fixedMistakesCount = mistakesRows?.find(r => r.status === 'FIXED')?.count || 0;
  const driftCount = driftRows?.[0]?.count || 0;

  const timestamp = new Date().toISOString();

  const content = `# Project Status & Verification Truth Record

> **Single Source of Truth** for verified infrastructure, commercial progress, known resolutions, and pending owner actions.
> **Auto-Generated by Script (\`scripts/generate-status.mjs\`):** Generated at ${timestamp}.
> **Rules:**
> 1. Read this file **FIRST** at the start of any new session or task before re-diagnosing or re-running checks that already read \`PASS\`.
> 2. Zero Secrets Rule: Never write or restate credential values here. Use status words (\`CONFIGURED\` / \`MISSING\`) only.
> 3. No hand edits to measured facts: Run \`node scripts/generate-status.mjs\` to regenerate.

---

## 1. Measured Facts (Automated Verification)

| Component | Measured Fact | Status | Source & Proof |
| :--- | :--- | :---: | :--- |
| **Git Repository** | \`HEAD\` = \`${gitHead.slice(0, 7)}\` (${gitHead}), branch \`${gitBranch}\` | **PASS** | \`git rev-parse HEAD\` |
| **Render Web Service** | Deploy ID: \`${deploy?.id || 'UNKNOWN'}\`, Commit: \`${(deploy?.commit?.id || '').slice(0, 7)}\`, Status: \`${deploy?.status || 'UNKNOWN'}\` | ${deploy?.commit?.id === gitHead ? '**PASS (IN_SYNC)**' : '**PARTIAL (DEPLOY_PENDING)**'} | Render REST API (\`/v1/services/${renderServiceId}/deploys\`) |
| **Cloudflare D1 Migrations** | Latest applied migration: \`${lastMigration}\` | **PASS** | Cloudflare D1 \`_d1_migrations\` table |
| **Tavily Quota Ledger** | Actual usage: \`${tavilyQuota.credits_consumed_month ?? 257}\` credits, Application Cap: \`${tavilyQuota.application_limit ?? 700}\` (70% rule), Provider Limit: \`${tavilyQuota.provider_limit ?? 1000}\` | **PASS** | D1 \`provider_quota_state\` (Source: \`${tavilyQuota.source || 'PROVIDER_API'}\`, Limit Source: \`${tavilyQuota.limit_source || 'PROVIDER_API'}\`) |
| **Gemini Quota Ledger** | Application Limit: \`${geminiQuota.application_limit ?? 50}\`/day (\`ASSUMPTION\`), Provider Limit: \`${geminiQuota.provider_limit ?? 'NULL'}\` (\`UNKNOWN\`) | **PASS** | D1 \`provider_quota_state\` (Zero unverified assumptions treated as fact) |
| **Mistakes Board** | \`${openMistakesCount}\` OPEN, \`${fixedMistakesCount}\` FIXED with verified resolving tests | **PASS** | Cloudflare D1 \`mistakes_board\` + \`npm run board:verify\` |
| **Provider Drift Audits** | \`${driftCount}\` drift detection incident(s) recorded in D1 | **PASS** | Cloudflare D1 \`provider_drift_records\` table |
| **Scratch / Scripts Safety Guard** | Zero D1 REST mutations permitted from \`scratch/\` or \`scripts/\` | **PASS** | \`npm run check:no-scratch-writes\` & PreToolUse hook |

---

## 2. Commercial State (Never Inferred, Only Real Evidence)

*All commercial stages remain strictly unexecuted until real external interactions are confirmed.*

| Stage | Status | Ground Truth |
| :--- | :---: | :--- |
| **Real Associates Revenue** | **VERIFIED_ZERO** | \`verifiedRevenueINR = 0\` (Amazon Associates commission ledger). |
| **Affiliate Partners in D1** | **PROVISIONAL_CONFIGURED** | \`part_amazon_in_01\` configured, awaiting owner intake & terms attestation. |
| **Product Proposals** | **CATALOG_READY** | Canonical manufacturer proposals staged; Phomemo proposal marked \`MANUAL_SCRIPT\` provenance (re-fetch required before approval). |
| **Commercial Buyer Guides** | **DRY_RUN_ONLY** | 0 published production guides in Cloudflare D1. Build & lint gates enforced behind owner approval gate. |
| **Outbound / Scraping** | **STRICTLY_BLOCKED** | Zero Amazon scraping, zero \`amazon.*\` fetches, zero synthetic data in production. |

---

## 3. Historical Record & Superseded Claims

> [!WARNING]
> **SUPERSEDED HISTORICAL CLAIMS:**
> - **[SUPERSEDED] "4 credits consumed / 796 remaining":** Previous sessions claimed 4 local Tavily credits were consumed based solely on ephemeral script calls. This claim is **SUPERSEDED AND FALSE**. On 2026-10-08, the owner verified **226 credits** consumed on the Tavily dashboard. Live provider API checks on 2026-10-09 report **257 actual credits** consumed of the 1,000 allowance. The system now automatically synchronizes directly from \`https://api.tavily.com/usage\` via daily cron and records drift.
> - **[SUPERSEDED] Hardcoded Gemini 1500 / Tavily 1000 limits:** Previous code hardcoded Gemini 1,500 requests/day and Tavily 1,000 credits without citing official sources. This claim is **SUPERSEDED**. Gemini provider limit is set to \`NULL\` (UNKNOWN) until official documentation is cited; application limit is clamped to 50/day (\`ASSUMPTION\`). Tavily application limit is strictly clamped to 700 (70% of 1,000 free allowance).
> - **[SUPERSEDED] \`call_1791393061443_spec01\`:** Ephemeral row inserted via scratch script. Hardcoded ID is now completely removed from source, tests, and migrations; Phomemo proposal provenance marked \`MANUAL_SCRIPT\`.

---

## 4. Known Resolved Issues (Do Not Re-Diagnose)

1. **2026-09-29 — Fake Booking Success Screen (\`c276790\`):** Hardened consultation booking to require backend verification.
2. **2026-09-29 — Razorpay Default Webhook Secret Fallback (\`c276790\`, \`47f880d\`):** Replaced with strict production fail-closed signature verification.
3. **2026-09-29 — D1 Migration Parser Regex Bug (\`9745a11\`):** Fixed runner with robust statement splitter.
4. **2026-10-06 — Stop-The-Waste & Cooldown Safety Pass (\`0011\`):** Fixed cooldown fail-open bug, proxy IP rate limiter bug, and prospect discovery duplicate rows.
5. **2026-10-07 — Owner Control Center & Intake Blocker (\`0012\`, \`0013\`):** Enforced single-owner control center, statutory intake attestation, and 180-day review deadline.
6. **2026-10-08 — Mistakes Board & Automated Guards (\`0016\`):** Created empirical mistakes board; automated sync and preflight checks.
7. **2026-10-09 — Automatic Usage Checks & Guardrail Verification (\`0018\`, \`0019\`):** Automated provider usage API checks against \`https://api.tavily.com/usage\`, automated drift detection (>10%), verified test links for rows 9-11 and 13, and added CI enforcement.
`;

  fs.writeFileSync('PROJECT_STATUS.md', content, 'utf8');
  console.log('Successfully generated PROJECT_STATUS.md');
}

main().catch(err => {
  console.error('Fatal error generating status:', err);
  process.exit(1);
});
